apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: volunteer-shifts2
  namespace: colossus-volunteer-shifts2
  labels:
    app: volunteer-shifts2
    managed-by: colossus
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: ubuntu.desmana-truck.ts.net
      http:
        paths:
          - path: /volunteer-shifts2(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: volunteer-shifts2
                port:
                  number: 80
  tls:
    - hosts:
        - ubuntu.desmana-truck.ts.net
      secretName: colossus-shared-tls
